config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  get '/Login', to: 'sessions#new'
  get '/Signup', to: 'users#new'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :tags, only: [:index, :show]
    resources :notes, except: [:new, :edit] do
      resources :tags, only: [:destroy, :create]
    end
    resources :notebooks, except: [:new, :edit]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :notes,
    foreign_key: :author_id

  has_many :notebooks,
    foreign_key: :author_id

  has_many :tags, through: :notes

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logout

  def new
    @user = User.new()
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      Notebook.create!(author_id: @user.id, title: "First Notebook")
      login!(@user)
      redirect_to "/#/home"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<header class="sign-in">
  <div class="logo-image"></div>
  <h1>Create Account</h1>
</header>

<div class="sign-in">
  <form  action="<%= users_url %>" method="post">
    <%= auth_token %>

    <label>Username or Email:
      <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>

    <label>Create a Password:
      <input type="password" name="user[password]">
      <ul>
        <% if flash[:errors] %>
          <% flash[:errors].each do |error| %>
            <li><%= error + "." %></li>
          <% end %>
        <% end %>
      </ul>
    </label>

    <button type="submit">Create Account</button>

  </form>
</div>

<footer class="sign-in">
  <span>Already have an account?</span>
  <a href="<%= new_session_url %>">Sign in</a>
</footer>